import { Resend } from 'resend';

export interface ErrorReportEmail {
  errorMessage: string;
  stack?: string;
  route: string;
  timestamp: string;
  userAgent: string;
  userContext: string;
  fix?: string;
}

export async function sendErrorReportEmail(data: ErrorReportEmail) {
  const devEmail = process.env.DEV_EMAIL || 'dev@gouache.art';
  const resendApiKey = process.env.RESEND_API_KEY;
  const fromAddress = process.env.RESEND_FROM_EMAIL || 'Hue <hue@gouache.art>';
  
  if (!resendApiKey) {
    console.error('⚠️ Email not configured: RESEND_API_KEY required');
    console.log('📧 Would send email to:', devEmail);
    console.log('📋 Error report:', data);
    return { success: false, error: 'Email not configured' };
  }

  try {
    const resend = new Resend(resendApiKey);
    
    const emailBody = `
Hey gouache dev-team,

A user encountered an error on the platform. Here's the full report:

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Error Message: ${data.errorMessage}
Route: ${data.route}
Timestamp: ${data.timestamp}
User Agent: ${data.userAgent}

${data.stack ? `Stack Trace:\n${data.stack}` : 'No stack trace available'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
USER CONTEXT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${data.userContext}

${data.fix ? `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SUGGESTED FIX
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${data.fix}
` : ''}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This report was automatically generated by Hue, the AI-powered error detection system.

`;

    const html = `
      <div style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 800px; margin: 0 auto; color: #111827;">
        <h2 style="font-size: 24px; font-weight: 700; margin-bottom: 8px;">Hey gouache dev-team,</h2>
        <p style="font-size: 16px; line-height: 1.5; margin-bottom: 24px;">A user encountered an error on the platform. Here's the full report:</p>
        
        <div style="background: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #ef4444;">
          <h3 style="color: #ef4444; margin-top: 0; font-size: 18px; font-weight: 600;">ERROR DETAILS</h3>
          <p style="margin: 8px 0;"><strong>Error Message:</strong> ${data.errorMessage}</p>
          <p style="margin: 8px 0;"><strong>Route:</strong> ${data.route}</p>
          <p style="margin: 8px 0;"><strong>Timestamp:</strong> ${data.timestamp}</p>
          <p style="margin: 8px 0;"><strong>User Agent:</strong> ${data.userAgent}</p>
          ${data.stack ? `<pre style="background: #1f2937; color: #fff; padding: 12px; border-radius: 4px; overflow-x: auto; font-size: 12px; margin-top: 12px;">${data.stack}</pre>` : '<p style="margin-top: 12px;">No stack trace available</p>'}
        </div>
        
        <div style="background: #eff6ff; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #3b82f6;">
          <h3 style="color: #3b82f6; margin-top: 0; font-size: 18px; font-weight: 600;">USER CONTEXT</h3>
          <p style="white-space: pre-wrap; margin: 0;">${data.userContext}</p>
        </div>
        
        ${data.fix ? `
        <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #10b981;">
          <h3 style="color: #10b981; margin-top: 0; font-size: 18px; font-weight: 600;">SUGGESTED FIX</h3>
          <pre style="background: #1f2937; color: #fff; padding: 12px; border-radius: 4px; overflow-x: auto; font-size: 12px; margin-top: 12px;">${data.fix}</pre>
        </div>
        ` : ''}
        
        <p style="color: #6b7280; font-size: 12px; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
          This report was automatically generated by Hue, the AI-powered error detection system.
        </p>
      </div>
    `;

    const result = await resend.emails.send({
      from: fromAddress,
      to: devEmail,
      subject: '🐛 Gouache App Bug + Fix',
      text: emailBody,
      html: html,
    });

    if (result.error) {
      console.error('❌ Resend API error:', result.error);
      return { success: false, error: result.error.message || 'Failed to send email' };
    }

    console.log('✅ Error report email sent:', result.data?.id);
    return { success: true, messageId: result.data?.id };
  } catch (error: any) {
    console.error('❌ Failed to send error report email:', error);
    return { success: false, error: error.message || 'Unknown error' };
  }
}
